=== NagaBC933/ucrepo/masterSchemas/definitions/Type.V1.0.0.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema#",
    "$id": "https://github.build.ge.com/DPM/em-central-repo/blob/convertWordToJson/masterSchemas/definitions/Type.V1.0.0.json",
    "title": "Type Definition Schema",
    "type": "object",
    "properties": {
        "name": {
            "type": "string"
        },
        "description": {
            "type": "string"
        },
        "level": {
            "type": "string",
            "enum": [
                "ASSET",
                "SEGMENT",
                "SITE",
                "ENTERPRISE"
            ]
        },
        "variables": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "description": {
                        "type": "string"
                    },
                    "dataType": {
                        "type": "string",
                        "enum": [
                            "numeric",
                            "string",
                            "boolean"
                        ]
                    },
                    "mandatory": {
                        "type": "boolean",
                        "description": "If the variable is mandatory, it should be included in all the templates. Else, the variable can be excluded in non-base templates."
                    },
                    "variableType": {
                        "type": "string",
                        "enum": [
                            "static",
                            "dynamic"
                        ]
                    },
                    "euName": {
                        "type": "string",
                        "description": "Reference of the unit of measure."
                    }
                },
                "required": [
                    "name",
                    "dataType",
                    "mandatory",
                    "variableType",
                    "euName"
                ]
            }
        },
        "containments": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "alias": {
                        "type": "string"
                    },
                    "containedType": {
                        "type": "string"
                    },
                    "containedTemplate": {
                        "type": "string"
                    },
                    "description": {
                        "type": "string"
                    },
                    "mandatory": {
                        "type": "boolean",
                        "description": "If the containment is mandatory, it should be included in all the templates. Else, containment can be excluded in non-base templates."
                    },
                    "aliasSubParamValues": {
                        "type": "array",
                        "description": "List of Substitution Parameters and their values that belong to the contained Type, used for overriding default values specified in the Type's template.",
                        "items": {
                            "type": "object",
                            "properties": {
                                "ID": {
                                    "type": "string",
                                    "description": "Substitution Parameter ID that is defined in the Type's template."
                                },
                                "Value": {
                                    "type": "string",
                                    "description": "Value of the Parameter specified as string."
                                }
                            },
                            "required": ["ID","Value"]
                        }
                    }
                },
                "required": [
                        "alias",
                        "containedType",
                        "containedTemplate",
                        "mandatory",
                        "description",
                        "aliasSubParamValues"
                    ]
                }
            
        }, 
        "substitutionParameters": {
            "$ref": "#/definitions/SubstitutionParameters"
          }
        },
        
        "required": [
            "name",
            "variables",
            "containments"
        ],

    "definitions": {
    "SubstitutionParameters": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "dataType": {
            "type": "string",
            "enum": ["numeric", "boolean", "string"]
          },
          "description": {
            "type": "string"
          },
          "defaultValue": {
            "type": "string"
          },
          "instantiationType": {
            "type": "string",
            "enum": ["Hidden","Optional","Readonly","Required","Static","StaticDisplay"]
          },
          "reference": {
            "type": "boolean"
          },
          "prompt": {
            "type": "string"
          },
          "helpString": {
            "type": "string"
          },
          "browserType": {
            "type": "string",
            "enum":["","ALARM_CLASS","DEVICE","MEASUNIT","POINT","PORT","RESOURCE","ROLE","USER"]
          },
          "order": {
            "type": "number"
          },
          "propertyPage": {
            "type": "string"
          }
        },
        "required": [
          "name",
          "dataType",
          "defaultValue"
        ]
      }
    }
  }
    }

=== NagaBC933/ucrepo/globalTypeDefinitions/PUMPTRAIN/definition/TypeDef.json
{
  "containments" : 
  [
    {
      "alias" : "MOTOR1",
      "aliasSubParamValues" : 
      [
        {
          "ID" : "$DEVICE_ID",
          "Value" : "{..\\$DEVICE_ID}"
        },
        {
          "ID" : "$RESOURCE_ID",
          "Value" : "{..\\$RESOURCE_ID}"
        },
        {
          "ID" : "$ADDRESS",
          "Value" : "{..\\$ADDRESS}.Motor1"
        }
      ],
      "containedTemplate" : "Base",
      "containedType" : "MOTOR",
      "description" : "",
      "mandatory" : true
    },
    {
      "alias" : "MOTOR2",
      "aliasSubParamValues" : 
      [
        {
          "ID" : "$DEVICE_ID",
          "Value" : "{..\\$DEVICE_ID}"
        },
        {
          "ID" : "$RESOURCE_ID",
          "Value" : "{..\\$RESOURCE_ID}"
        },
        {
          "ID" : "$ADDRESS",
          "Value" : "{..\\$ADDRESS}.Motor2"
        }
      ],
      "containedTemplate" : "Base",
      "containedType" : "MOTOR",
      "description" : "",
      "mandatory" : true
    },
    {
      "alias" : "MOTOR3",
      "aliasSubParamValues" : 
      [
        {
          "ID" : "$DEVICE_ID",
          "Value" : "{..\\$DEVICE_ID}"
        },
        {
          "ID" : "$RESOURCE_ID",
          "Value" : "{..\\$RESOURCE_ID}"
        },
        {
          "ID" : "$ADDRESS",
          "Value" : "{..\\$ADDRESS}.Motor3"
        }
      ],
      "containedTemplate" : "Base",
      "containedType" : "MOTOR",
      "description" : "",
      "mandatory" : true
    },
    {
      "alias" : "PUMP1",
      "aliasSubParamValues" : 
      [
        {
          "ID" : "$DEVICE_ID",
          "Value" : "{..\\$DEVICE_ID}"
        },
        {
          "ID" : "$RESOURCE_ID",
          "Value" : "{..\\$RESOURCE_ID}"
        },
        {
          "ID" : "$ADDRESS",
          "Value" : "{..\\$ADDRESS}.Pump1"
        }
      ],
      "containedTemplate" : "Base",
      "containedType" : "PUMP",
      "description" : "",
      "mandatory" : true
    },
    {
      "alias" : "PUMP2",
      "aliasSubParamValues" : 
      [
        {
          "ID" : "$DEVICE_ID",
          "Value" : "{..\\$DEVICE_ID}"
        },
        {
          "ID" : "$RESOURCE_ID",
          "Value" : "{..\\$RESOURCE_ID}"
        },
        {
          "ID" : "$ADDRESS",
          "Value" : "{..\\$ADDRESS}.Pump2"
        }
      ],
      "containedTemplate" : "Base",
      "containedType" : "PUMP",
      "description" : "",
      "mandatory" : true
    },
    {
      "alias" : "PUMP3",
      "aliasSubParamValues" : 
      [
        {
          "ID" : "$DEVICE_ID",
          "Value" : "{..\\$DEVICE_ID}"
        },
        {
          "ID" : "$RESOURCE_ID",
          "Value" : "{..\\$RESOURCE_ID}"
        },
        {
          "ID" : "$ADDRESS",
          "Value" : "{..\\$ADDRESS}.Pump3"
        }
      ],
      "containedTemplate" : "Base",
      "containedType" : "PUMP",
      "description" : "",
      "mandatory" : true
    }
  ],
  "description" : "Pump train — 3 pumps + 3 motors",
  "level" : "ASSET",
  "name" : "PUMPTRAIN",
  "variables" : []
}

=== NagaBC933/ucrepo/globalTypeDefinitions/OUTLETPUMP/definition/TypeDef.json
{
  "containments" : [],
  "description" : "",
  "level" : "ASSET",
  "name" : "OUTLETPUMP",
  "variables" : 
  [
    {
      "dataType" : "numeric",
      "description" : "",
      "euName" : "m3/h",
      "mandatory" : true,
      "name" : "PUMPFLOWRATE",
      "variableType" : "dynamic"
    }
  ]
}

=== NagaBC933/ucrepo/globalTypeDefinitions/WTP/definition/TypeDef.json
{
  "containments" : 
  [
    {
      "alias" : "CHLORINATION",
      "aliasSubParamValues" : 
      [
        {
          "ID" : "$DEVICE_ID",
          "Value" : "{..\\$DEVICE_ID}"
        },
        {
          "ID" : "$RESOURCE_ID",
          "Value" : "{..\\$RESOURCE_ID}"
        },
        {
          "ID" : "$ADDRESS",
          "Value" : "{..\\$ADDRESS}Treatment.ChlorinationSystem"
        }
      ],
      "containedTemplate" : "Base",
      "containedType" : "CHLORINATION",
      "description" : "",
      "mandatory" : true
    },
    {
      "alias" : "CLEARWELL",
      "aliasSubParamValues" : 
      [
        {
          "ID" : "$DEVICE_ID",
          "Value" : "{..\\$DEVICE_ID}"
        },
        {
          "ID" : "$RESOURCE_ID",
          "Value" : "{..\\$RESOURCE_ID}"
        },
        {
          "ID" : "$ADDRESS",
          "Value" : "{..\\$ADDRESS}ClearWell"
        }
      ],
      "containedTemplate" : "Base",
      "containedType" : "CLEARWELL",
      "description" : "",
      "mandatory" : true
    },
    {
      "alias" : "DOSINGPUMP",
      "aliasSubParamValues" : 
      [
        {
          "ID" : "$DEVICE_ID",
          "Value" : "{..\\$DEVICE_ID}"
        },
        {
          "ID" : "$RESOURCE_ID",
          "Value" : "{..\\$RESOURCE_ID}"
        },
        {
          "ID" : "$ADDRESS",
          "Value" : "{..\\$ADDRESS}Treatment.ChemicalDosingSystem.DosingPump"
        }
      ],
      "containedTemplate" : "Base",
      "containedType" : "DOSINGPUMP",
      "description" : "",
      "mandatory" : true
    },
    {
      "alias" : "FILTER",
      "aliasSubParamValues" : 
      [
        {
          "ID" : "$DEVICE_ID",
          "Value" : "{..\\$DEVICE_ID}"
        },
        {
          "ID" : "$RESOURCE_ID",
          "Value" : "{..\\$RESOURCE_ID}"
        },
        {
          "ID" : "$ADDRESS",
          "Value" : "{..\\$ADDRESS}Filtration.Filter"
        }
      ],
      "containedTemplate" : "Base",
      "containedType" : "FILTER",
      "description" : "",
      "mandatory" : true
    },
    {
      "alias" : "FILTRATIONCONTROL",
      "aliasSubParamValues" : 
      [
        {
          "ID" : "$DEVICE_ID",
          "Value" : "{..\\$DEVICE_ID}"
        },
        {
          "ID" : "$RESOURCE_ID",
          "Value" : "{..\\$RESOURCE_ID}"
        },
        {
          "ID" : "$ADDRESS",
          "Value" : "{..\\$ADDRESS}Treatment.FiltrationControlSystem"
        }
      ],
      "containedTemplate" : "Base",
      "containedType" : "FILTRATIONCONTROL",
      "description" : "",
      "mandatory" : true
    },
    {
      "alias" : "INTAKE",
      "aliasSubParamValues" : 
      [
        {
          "ID" : "$DEVICE_ID",
          "Value" : "{..\\$DEVICE_ID}"
        },
        {
          "ID" : "$RESOURCE_ID",
          "Value" : "{..\\$RESOURCE_ID}"
        },
        {
          "ID" : "$ADDRESS",
          "Value" : "{..\\$ADDRESS}Intake"
        }
      ],
      "containedTemplate" : "Base",
      "containedType" : "INTAKE",
      "description" : "",
      "mandatory" : true
    },
    {
      "alias" : "OUTLETPUMP",
      "aliasSubParamValues" : 
      [
        {
          "ID" : "$DEVICE_ID",
          "Value" : "{..\\$DEVICE_ID}"
        },
        {
          "ID" : "$RESOURCE_ID",
          "Value" : "{..\\$RESOURCE_ID}"
        },
        {
          "ID" : "$ADDRESS",
          "Value" : "{..\\$ADDRESS}"
        }
      ],
      "containedTemplate" : "Base",
      "containedType" : "OUTLETPUMP",
      "description" : "",
      "mandatory" : true
    }
  ],
  "description" : "Water Treatment Plant",
  "level" : "ASSET",
  "name" : "WTP",
  "variables" : 
  [
    {
      "dataType" : "numeric",
      "description" : "",
      "euName" : "m3/h",
      "mandatory" : true,
      "name" : "OUTFLOW",
      "variableType" : "dynamic"
    }
  ]
}

=== NagaBC933/ucrepo/globalTypeDefinitions/CHLORINATION/definition/TypeDef.json
{
  "containments" : [],
  "description" : "",
  "level" : "ASSET",
  "name" : "CHLORINATION",
  "variables" : 
  [
    {
      "dataType" : "numeric",
      "description" : "",
      "euName" : "mg/l",
      "mandatory" : true,
      "name" : "CHLORINEPV",
      "variableType" : "dynamic"
    },
    {
      "dataType" : "numeric",
      "description" : "",
      "euName" : "mg/l",
      "mandatory" : true,
      "name" : "CHLORINESP",
      "variableType" : "dynamic"
    }
  ]
}

=== NagaBC933/ucrepo/globalTypeDefinitions/FILTRATIONCONTROL/definition/TypeDef.json
{
  "containments" : [],
  "description" : "",
  "level" : "ASSET",
  "name" : "FILTRATIONCONTROL",
  "variables" : 
  [
    {
      "dataType" : "numeric",
      "description" : "",
      "euName" : "NTU",
      "mandatory" : true,
      "name" : "TURBIDITYPV",
      "variableType" : "dynamic"
    },
    {
      "dataType" : "numeric",
      "description" : "",
      "euName" : "NTU",
      "mandatory" : true,
      "name" : "TURBIDITYSP",
      "variableType" : "dynamic"
    }
  ]
}

=== NagaBC933/ucrepo/globalTypeDefinitions/DOSINGPUMP/definition/TypeDef.json
{
  "containments" : [],
  "description" : "",
  "level" : "ASSET",
  "name" : "DOSINGPUMP",
  "variables" : 
  [
    {
      "dataType" : "numeric",
      "description" : "",
      "euName" : "mg/l",
      "mandatory" : true,
      "name" : "CHEMICALDOSERATE",
      "variableType" : "dynamic"
    }
  ]
}

=== NagaBC933/ucrepo/globalTypeDefinitions/FILTER/definition/TypeDef.json
{
  "containments" : [],
  "description" : "",
  "level" : "ASSET",
  "name" : "FILTER",
  "variables" : 
  [
    {
      "dataType" : "numeric",
      "description" : "",
      "euName" : "bar",
      "mandatory" : true,
      "name" : "INLETPRESSURE",
      "variableType" : "dynamic"
    },
    {
      "dataType" : "numeric",
      "description" : "",
      "euName" : "m3/h",
      "mandatory" : true,
      "name" : "OUTFLOW",
      "variableType" : "dynamic"
    },
    {
      "dataType" : "numeric",
      "description" : "",
      "euName" : "bar",
      "mandatory" : true,
      "name" : "OUTLETPRESSURE",
      "variableType" : "dynamic"
    }
  ]
}
